apiVersion: v1
kind: Service
metadata:
  name: orderertwoorg
spec:
  selector:
    app: orderertwoorg
  ports:
   - protocol: TCP
     targetPort: 7050
     port: 7050
     nodePort: 32001
     name: orderer-port
  type: NodePort