apiVersion: v1
kind: Service
metadata:
  name: peer0-org1-service
spec:
  selector:
    app: peer0-org1
  ports:
  - protocol: TCP
    targetPort: 7051
    port: 7051
    nodePort: 32202
    name: peer0-org1-port
  - protocol: TCP
    targetPort: 7053
    port: 7053
    nodePort: 32204
    name: peer0-1-event
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: peer0-org2-service
spec:
  selector:
    app: peer0-org2
  ports:
  - protocol: TCP
    targetPort: 7051
    port: 7051
    nodePort: 32012
    name: peer0-port
  - protocol: TCP
    targetPort: 7053
    port: 7053
    nodePort: 32014
    name: peer0-event
  type: NodePort
