apiVersion: apps/v1
kind: Deployment
metadata:
  name: peer0org1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: peer0-org1
  template:
    metadata:
      labels:
        app: peer0-org1
    spec:
      hostname: peer0-org1
      volumes:
      - name: nfs-volume
        nfs: 
        # URL for the NFS server
         server: 192.71.82.75 # Change this!
         path: /home/fab/twoorgfabric/artifacts/

      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock   
      containers:
      - args:
        - peer
        - node
        - start
        env:
        - name: CORE_CHAINCODE_LOGGING_LEVEL
          value: info
        - name: CORE_LOGGING_PEER
          value: info
        - name: CORE_PEER_ADDRESS
          value: 0.0.0.0:7051
        - name: CORE_PEER_GOSSIP_BOOTSTRAP
          value: 0.0.0.0:7051
        - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
          value: 0.0.0.0:7051
        - name: CORE_PEER_GOSSIP_ORGLEADER
          value: "false"
        - name: CORE_PEER_GOSSIP_USELEADERELECTION
          value: "true"
        - name: CORE_PEER_ID
          value: 0.0.0.0
        - name: CORE_PEER_LOCALMSPID
          value: Org1MSP
        - name: CORE_PEER_MSPCONFIGPATH
          value: /home/fab/twoorgfabric/artifacts/crypto/crypto-config/peerOrganizations/Org1.twoorg.com/peers/peer0.Org1.twoorg.com/msp
        - name: CORE_PEER_PROFILE_ENABLED
          value: "true"
        - name: CORE_PEER_TLS_CERT_FILE
          value: /home/fab/twoorgfabric/artifacts/crypto/crypto-config/peerOrganizations/Org1.twoorg.com/peers/peer0.Org1.twoorg.com/tls/server.crt
        - name: CORE_PEER_TLS_ENABLED
          value: "false"
        - name: CORE_PEER_TLS_KEY_FILE
          value: /home/fab/twoorgfabric/artifacts/crypto/crypto-config/peerOrganizations/Org1.twoorg.com/peers/peer0.Org1.twoorg.com/tls/server.key
        - name: CORE_PEER_TLS_ROOTCERT_FILE
          value: /home/fab/twoorgfabric/artifacts/crypto/crypto-config/peerOrganizations/Org1.twoorg.com/peers/peer0.Org1.twoorg.com/tls/ca.crt
        - name: ORDERER_URL
          value: "192.71.82.75:32001"
        - name: CORE_VM_ENDPOINT
          value: unix:///host/var/run/docker.sock
        image: hyperledger/fabric-peer
        name: peer0-org1
        ports:
        - containerPort: 7051
        - containerPort: 7053
        volumeMounts:
           - mountPath: "/home/fab/twoorgfabric/artifacts/"
             name: nfs-volume 
           - mountPath: "/host/var/run/docker.sock"  
             name: docker-socket             
        resources: {}
      restartPolicy: Always 
