NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.Org2.twoorg.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.Org2.twoorg.com-cert.pem
    OrganizationalUnitIdentifier: peer
